DefaultContentLanguage = "en"
languageCode = "ja"
title = 'rakano blog'
theme = "mainroad"
paginate = 5
googleAnalytics = "UA-XXX-XXX"
enableRobotsTXT = false
hasCJKLanguage = true
summaryLength = 100

[Params]
highlightColor = "#abcdef"
twitter_cards = true
readmore = true
pager = true
post_meta = ["date", "categories"]
opengraph = true
images = ["/img/default.webp"]
dateformat = "2006-01-02"
googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700&display=swap"
customCSS = ["css/custom.css"]

[Params.sidebar]
home = "right"
list = "right"
single = true
widgets = ["recent", "social", "categories"]

[Params.widgets]
recent_num = 5

[Params.widgets.social]
twitter = "la_carno"

[[Menus.main]]
Name = "Top"
URL = "/"
weight = 1

[[Menus.main]]
Name = "Blog"
URL = "/categories/blog/"
weight = 2

[[Menus.main]]
Name = "Programming"
URL = "/categories/programming/"
weight = 3

[[Menus.main]]
Name = "PC"
URL = "/categories/pc/"
weight = 4

[[Menus.main]]
Name = "Procedure"
URL = "/categories/procedure/"
weight = 5

[[Menus.footer]]
Name = "Privacy"
URL = "/privacy/"